export const legalWords = {
    opening: `Fast Fix Computer Repair, LLC Terms of Service Agreement by signature is required before Fast Fix Computer Repair, LLC may render any service(s).`,
    installAuth: `INSTALLATION AUTHORIZATION For on-site services, a person at least 18 years of age must be present during the entire time period services are provided. If no adult is present when we arrive, services will be denied and a $99 cancellation charge will be assessed.`,
    responsibility: `RESPONSIBLITY It is your responsibility to back up all software and data on your computer's data drive(s) and/or any other storage devices before we arrive. Fast Fix Computer Repair, LLC and/or its third-party service provider shall not be responsible at any time for any loss, alteration, or corruption of any software, data, or files.`,
    access: `ACCESS We must have 1) access to your residence or business and the computer(s) and/or peripheral(s) to be serviced, 2) your consent and cooperation to enter your residence or business, 3) a safe working environment, work space, and 4) electrical power. If we determine that these conditions have not been met, services will be denied and a $99 cancellation charge assessed.`,
    limitations: `SERVICE LIMITATIONS Fast Fix Computer Repair, LLC and/or its third-party service providers reserve the right to refrain from providing any or all services ordered and refund the customer's payment, wholly or in part, if minimum system requirements are not met or if technical conditions (such as wiring difficulties or physical barriers) or customer requirements are unusual, extensive, or beyond the scope of this service agreement as reasonably determined by Fast Fix Computer Repair, LLC and/or its third-party service provider. Data Recovery services are not guaranteed nor refundable once service is rendered, Fast Fix Computer Repair, LLC and/or its third-party service providers cannot guarantee all data will be recovered.`,
    majeure: `FORCE MAJEURE If Fast Fix Computer Repair, LLC and/or its third-party service provider's ability to render services is impaired by circumstances beyond the control of Fast Fix Computer Repair, LLC and/or its third-party service provider, Fast Fix Computer Repair, LLC and/or its third-party service provider may choose not to provide services.`,
    remedy: `LIMITATION OF REMEDY Under no circumstances shall Fast Fix Computer Repair, LLC, and/or its third-party service provider be liable to you or any other person for any damages, including without limitation any indirect, incidental, special or consequential damages, expenses costs, profits, lost savings or earnings, lost or corrupted data, or other liability arising out of or related to the services provided by Fast Fix Computer Repair, LLC and/or its third-party service provider or out of the installation, de-installation, use of, or inability to use your computer equipment, hardware, peripherals, or the network as a result of the services provided hereunder. Fast Fix Computer Repair, LLC shall not be liable for any failure or delay in performance due to any cause beyond its control. If Fast Fix Computer Repair, LLC’s ability to render services is impaired by your failure to cooperate or circumstances beyond the control of Fast Fix Computer Repair, LLC, Fast Fix Computer Repair, LLC may choose not to provide services. Service can also be denied if dangerous or unhealthy conditions are present including possible code violations. For any un-installation services provided, Fast Fix Computer Repair, LLC shall not be responsible for repairing any damage or changes made to your residence.`,
    liability: `LIMITATION OF LIABILITY & RELEASE By signing below, you agree to release and hold harmless, Fast Fix Computer Repair, LLC, and/or its third-party service provider from and against any loss, liability, or damage, including without limitation, any indirect, incidental, special or consequential damages, expense, costs, profits, lost savings or earnings or liability that you, the owner, or lessee may suffer arising out of, or related to, the services provided by Fast Fix Computer Repair, LLC. This includes but is not limited to data loss or lack of function in any component or element of your computer system and/or peripherals, any changes or alterations to your residence (for example, changes to walls, baseboards, floors, etc.) as a result of Fast Fix Computer Repair, LLC and/or its third-party service provider's agents, partners, and/or third-party service providers, regardless of the warranties, disclaimers, and waivers particular service and shall constitute liquidated damages and are a reasonable estimate of damages to you. Some states do not allow limitations or release of certain damages or liability, so the above limitation of liability and release may not apply to you.`,
    unclaimed: ` UNCLAIMED AND ABANDONED PROPERTY Your property must be retrieved by an authorized party within 30 days of service completion. If your property is not retrieved and remains unclaimed after 30 days of completion your property will be considered abandoned and ownership will be forfeited to Fast Fix Computer Repair, LLC.`,
    changes: `CHANGES, CANCELLATIONS AND REFUNDS To change your order: You must contact Fast Fix Computer Repair, LLC at (602) 935-8365. To cancel your order: You must contact Fast Fix Computer Repair, LLC at (602) 935-8365 at least 2 hours prior to the scheduled service time. In-store and/or phone, verbal or SMS approvals cannot be cancelled.`,
};
